language: node_js
node_js:
  - "9"

script:
  - npm run eslint
  - npm test

after_script:
  - npm install --save-dev codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=4fa9e6e08664069171a0a5106a61515a559d39bccfc074963e15eea99c6d12ef codeclimate-test-reporter < ./coverage/lcov.info